In [37]:
import pandas as pd
import numpy as np
import os
import datetime as dt
import calendar
from matplotlib import pyplot as plt
import scipy.stats as stats
import glob

import requests
import zipfile
import io
import pandas as pd
import time

In [179]:

df_kyuden_total = pd.DataFrame(columns=['DateTime','九電太陽想定値(kWh)','九電太陽実績値(kWh)','九電風力想定値(kWh)','九電風力実績値(kWh)'])

# 1-3が画翌年
# 単位はkWh
month_list =['4-6','7-9','10-12','1-3']
sheet_name_list = ['太陽光想定','太陽光実績','風力想定','風力実績']
col_names =np.array(list(range(49)),dtype='str')


for year in range(2018,2023):
    for month in month_list:
        for name_s in sheet_name_list[:]:

            df_read = pd.read_excel(f'../../卒論関連書類/データ/発電予測値/九州電力/td_{year}_{month}.xls',sheet_name=name_s,names=col_names)[3:]
                        # シート読み込みの初回にDatetime を作成する
            if name_s==sheet_name_list[0]:
                    # 一区切り分のデータをまとめるデータフレームの作成  
                df = pd.DataFrame(columns=['DateTime','九電太陽想定値(kWh)','九電太陽実績値(kWh)','九電風力想定値(kWh)','九電風力実績値(kWh)'])

                # ///読み取ったシートからTimeStampを制作する
                # 日付の抽出
                # Dates = df_read['0'].values
                # 時刻のリストを作る
                Times = np.array(list(range(0,48)))*30
                hours,mins = Times//60,Times%60

                datetime_list = []
                #日付と時刻を合わせたリストを作る
                for date in df_read['0']:
                    for i in range(48):

                        str_datetime = f'{date.year}/{date.month}/{date.day}/{hours[i]}/{mins[i]}'
                        datetime_list.append(dt.datetime.strptime(str_datetime,'%Y/%m/%d/%H/%M'))
                # ///
                df['DateTime'] = datetime_list
            else:
                pass

            # ここから上はシートの読み込み一回のみ一度のみの処理
            # ここから下はシートの数繰り返し
            values_list =[]
            for num in range(len(df_read)):
                values = df_read[num:num+1].values[0][1:]
                values_list.extend(values)
            if name_s=='太陽光想定':
                df['九電太陽想定値(kWh)']=values_list
            elif name_s=='太陽光実績':
                df['九電太陽実績値(kWh)']=values_list
            elif name_s=='風力想定':
                df['九電風力想定値(kWh)']=values_list
            elif name_s == '風力実績':
                df['九電風力実績値(kWh)']=values_list
            else:
                print('エラー九電')
        
        df_kyuden_total = pd.concat([df_kyuden_total,df],axis=0)

df_kyuden_total = df_kyuden_total.reset_index(drop=True)

FileNotFoundError: [Errno 2] No such file or directory: '../../卒論関連書類/データ/発電予測値/九州電力/td_2022_10-12.xls'

In [177]:
df_kyuden_total

,DateTime,九電太陽想定値(kWh),九電太陽実績値(kWh),九電風力想定値(kWh),九電風力実績値(kWh)
0,2018-04-01 00:00:00,0.0,0.0,5889.905000,8909.100000
1,2018-04-01 00:30:00,0.0,0.0,5642.430000,8909.100000
2,2018-04-01 01:00:00,0.0,0.0,5642.430000,6929.300000
3,2018-04-01 01:30:00,0.0,0.0,5444.450000,5939.400000
4,2018-04-01 02:00:00,0.0,0.0,5295.965000,5939.400000
...,...,...,...,...,...
70123,2022-03-31 21:30:00,0.0,0.0,75589.876734,80915.101876
70124,2022-03-31 22:00:00,0.0,0.0,78357.541014,82754.081464
70125,2022-03-31 22:30:00,0.0,0.0,76204.555661,85512.550846
70126,2022-03-31 23:00:00,0.0,0.0,76632.118415,89190.510023
70127,2022-03-31 23:30:00,0.0,0.0,70992.887509,80915.101876

In [174]:
df_read = pd.read_excel(f'../../卒論関連書類/データ/発電予測値/九州電力/td_{year}_{month}.xls',sheet_name='太陽光想定',names=col_names)[:]

In [175]:
df_read

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,（ｋＷｈ）
2,NaT,00:00:00,00:30:00,01:00:00,01:30:00,02:00:00,02:30:00,03:00:00,03:30:00,04:00:00,...,19:00:00,19:30:00,20:00:00,20:30:00,21:00:00,21:30:00,22:00:00,22:30:00,23:00:00,23:30:00
3,2021-01-01,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2021-01-02,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,2021-03-27,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
89,2021-03-28,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
90,2021-03-29,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
91,2021-03-30,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
92,2021-03-31,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [145]:
len(datetime_list)

4320

In [178]:
df_kyuden_total[50001:50020]

,DateTime,九電太陽想定値(kWh),九電太陽実績値(kWh),九電風力想定値(kWh),九電風力実績値(kWh)
50001,2021-02-05 16:30:00,536984.835869,204962.590,489.720040,5428.409
50002,2021-02-05 17:00:00,257087.086383,73619.216,489.720040,5428.409
50003,2021-02-05 17:30:00,13310.856202,0.000,488.944553,4652.922
50004,2021-02-05 18:00:00,0.000000,0.000,502.127833,2326.461
50005,2021-02-05 18:30:00,0.000000,0.000,487.781323,3101.948
50006,2021-02-05 19:00:00,0.000000,0.000,565.717767,4652.922
50007,2021-02-05 19:30:00,0.000000,0.000,887.157128,3101.948
50008,2021-02-05 20:00:00,0.000000,0.000,500.964602,5428.409
50009,2021-02-05 20:30:00,0.000000,0.000,4503.640752,3877.435
50010,2021-02-05 21:00:00,0.000000,0.000,4932.485064,6979.383
50011,2021-02-05 21:30:00,0.000000,0.000,5433.837409,2326.461
50012,2021-02-05 22:00:00,0.000000,0.000,6698.268962,5428.409
50013,2021-02-05 22:30:00,0.000000,0.000,7979.761230,3101.948
50014,2021-02-05 23:00:00,0.000000,0.000,13743.568358,7754.870
50015,2021-02-05 23:30:00,0.000000,0.000,18119.253755,10081.331
50016,2021-02-06 00:00:00,0.000000,0.000,4778.163151,9305.844
50017,2021-02-06 00:30:00,0.000000,0.000,5936.352985,13183.279
50018,2021-02-06 01:00:00,0.000000,0.000,6685.473427,14734.253
50019,2021-02-06 01:30:00,0.000000,0.000,8481.501319,17836.201

In [161]:
df[df_kyuden_total['九電太陽想定値(kWh)']>1]

/var/folders/c5/xmh5z7yd191cl82bdh1n_kzc0000gn/T/ipykernel_69018/1781067614.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df_kyuden_total['九電太陽想定値(kWh)']>1]

,DateTime,九電太陽想定値(kWh),九電太陽実績値(kWh),九電風力想定値(kWh),九電風力実績値(kWh)
12,2022-01-01 06:00:00,0.000000,0.000000,16061.403873,47433.469167
13,2022-01-01 06:30:00,0.000000,0.000000,15715.139548,41396.482182
14,2022-01-01 07:00:00,0.000000,1635.285337,14954.479188,35359.495197
15,2022-01-01 07:30:00,130529.293245,92393.621542,14878.154424,25010.374652
16,2022-01-01 08:00:00,517558.406280,419990.333110,14941.974001,16044.155339
...,...,...,...,...,...
4306,2022-03-31 17:00:00,169939.226467,73384.274709,84562.258144,96546.428375
4307,2022-03-31 17:30:00,66337.345885,29353.709884,85810.465540,106660.816109
4308,2022-03-31 18:00:00,2623.487821,6523.046641,85735.986866,118614.183432
4309,2022-03-31 18:30:00,0.000000,0.000000,91018.455733,125970.101784
4310,2022-03-31 19:00:00,0.000000,0.000000,90286.082112,115855.714050

In [144]:
df_kyuden_total['DateTime'].drop_duplicates()

0       2018-04-01 00:00:00
1       2018-04-01 00:30:00
2       2018-04-01 01:00:00
3       2018-04-01 01:30:00
4       2018-04-01 02:00:00
                ...
57115   2019-03-31 21:30:00
57116   2019-03-31 22:00:00
57117   2019-03-31 22:30:00
57118   2019-03-31 23:00:00
57119   2019-03-31 23:30:00
Name: DateTime, Length: 17520, dtype: datetime64[ns]

In [118]:
for date in df_read['0']:
    pass

In [122]:
date

0

In [123]:
df

Empty DataFrame
Columns: [DateTime, 九電太陽想定値(kWh), 九電太陽実績値(kWh), 九電風力想定値(kWh), 九電風力実績値(kWh)]
Index: []

In [124]:
year

2020

In [125]:
month

'1-3'

In [126]:
name_s

'太陽光想定'

In [127]:
df_read

,,,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
2021-01-01,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2021-01-02,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2021-01-03,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2021-01-04,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2021-01-05,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-27,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2021-03-28,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2021-03-29,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2021-03-30,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2021-03-31,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [92]:
# シート読み込みの初回にDatetime を作成する
if name_s=='太陽光想定':
        # 一区切り分のデータをまとめるデータフレームの作成  
    df = pd.DataFrame(columns=['DateTime','九電太陽想定値(kWh)','九電太陽実績値(kWh)','九電風力想定値(kWh)','九電風力実績値(kWh)'])

    # ///読み取ったシートからTimeStampを制作する
    # 日付の抽出
    Dates = df_read['0'].values
    # 時刻のリストを作る
    Times = np.array(list(range(0,48)))*30
    hours,mins = Times//60,Times%60

    datetime_list = []
    #日付と時刻を合わせたリストを作る
    for date in Dates:
        for i in range(48):

            str_datetime = f'{date.year}/{date.month}/{date.day}/{hours[i]}/{mins[i]}'
            datetime_list.append(dt.datetime.strptime(str_datetime,'%Y/%m/%d/%H/%M'))
    # ///
    df['DateTime'] = datetime_list
else:
    pass

# ここから上はシートの読み込み一回のみ一度のみの処理
# ここから下はシートの数繰り返し
values_list =[]
for num in range(len(df_read)):
    values = df_read[num:num+1].values[0][1:]
    values_list.extend(values)
if name_s=='太陽光想定':
    df['九電太陽想定値(kWh)']=values_list
elif name_s=='太陽光実績':
    df['九電太陽実績値(kWh)']=values_list
elif name_s=='風力想定':
    df['九電風力想定値(kWh)']=values_list
elif name_s == '風力実績':
    df['九電風力実績値(kWh)']=values_list
else:
    print('エラー九電')

In [94]:
df

                DateTime 九電太陽想定値(kWh) 九電太陽実績値(kWh) 九電風力想定値(kWh) 九電風力実績値(kWh)
0    2022-01-01 00:00:00          NaN          NaN          NaN          NaN
1    2022-01-01 00:30:00          NaN          NaN          NaN          NaN
2    2022-01-01 01:00:00          NaN          NaN          NaN          NaN
3    2022-01-01 01:30:00          NaN          NaN          NaN          NaN
4    2022-01-01 02:00:00          NaN          NaN          NaN          NaN
...                  ...          ...          ...          ...          ...
4315 2022-03-31 21:30:00          NaN          NaN          NaN          NaN
4316 2022-03-31 22:00:00          NaN          NaN          NaN          NaN
4317 2022-03-31 22:30:00          NaN          NaN          NaN          NaN
4318 2022-03-31 23:00:00          NaN          NaN          NaN          NaN
4319 2022-03-31 23:30:00          NaN          NaN          NaN          NaN

[4320 rows x 5 columns]

In [77]:
df['DateTime'] = datetime_list

In [95]:
values_list =[]
for num in range(len(df_read)):
    values = df_read[num:num+1].values[0][1:]
    values_list.extend(values)
if name_s=='太陽光想定':
    df['九電太陽想定値(kWh)']=values_list
elif name_s=='太陽光実績':
    df['九電太陽実績値(kWh)']=values_list
elif name_s=='風力想定':
    df['九電風力想定値(kWh)']=values_list
elif name_s == '風力実績':
    df['九電風力実績値(kWh)']=values_list
else:
    print('エラー九電')

In [96]:
df

                DateTime 九電太陽想定値(kWh) 九電太陽実績値(kWh) 九電風力想定値(kWh)  九電風力実績値(kWh)
0    2022-01-01 00:00:00          NaN          NaN          NaN  57782.589713
1    2022-01-01 00:30:00          NaN          NaN          NaN  55195.309577
2    2022-01-01 01:00:00          NaN          NaN          NaN  52608.029440
3    2022-01-01 01:30:00          NaN          NaN          NaN  49158.322592
4    2022-01-01 02:00:00          NaN          NaN          NaN  49158.322592
...                  ...          ...          ...          ...           ...
4315 2022-03-31 21:30:00          NaN          NaN          NaN  80915.101876
4316 2022-03-31 22:00:00          NaN          NaN          NaN  82754.081464
4317 2022-03-31 22:30:00          NaN          NaN          NaN  85512.550846
4318 2022-03-31 23:00:00          NaN          NaN          NaN  89190.510023
4319 2022-03-31 23:30:00          NaN          NaN          NaN  80915.101876

[4320 rows x 5 columns]

In [83]:
df_read

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
3,2022-01-01 00:00:00,57782.589713,55195.309577,52608.02944,49158.322592,49158.322592,50883.176016,50883.176016,47433.469167,48295.895879,...,2587.280136,1724.853424,2587.280136,2587.280136,3449.706849,2587.280136,2587.280136,1724.853424,2587.280136,0
4,2022-01-02 00:00:00,1724.853424,862.426712,1724.853424,2587.280136,1724.853424,862.426712,1724.853424,862.426712,3449.706849,...,37084.348622,31909.788349,36221.92191,38809.202046,38809.202046,41396.482182,40534.05547,37946.775334,39671.628758,35359.495197
5,2022-01-03 00:00:00,34497.068485,30184.934925,27597.654788,25872.801364,25872.801364,23285.521228,25010.374652,22423.094515,26735.228076,...,41396.482182,36221.92191,43121.335607,50883.176016,58645.016425,56920.163001,61232.296561,58645.016425,64682.00341,63819.576698
6,2022-01-04 00:00:00,64682.00341,62094.723274,62957.149986,60369.869849,58645.016425,58645.016425,59507.443137,58645.016425,61232.296561,...,43121.335607,37084.348622,31909.788349,25872.801364,22423.094515,14661.254106,12936.400682,15523.680818,16386.107531,14661.254106
7,2022-01-05 00:00:00,18110.960955,17248.534243,21560.667803,16386.107531,17248.534243,16386.107531,16386.107531,16386.107531,15523.680818,...,49158.322592,50020.749304,54332.882864,55195.309577,54332.882864,50020.749304,51745.602728,45708.615743,45708.615743,48295.895879
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,2022-03-27 00:00:00,76317.652906,78156.632494,72639.69373,74478.673318,68961.734553,71720.203936,79995.612082,75398.163112,63444.795789,...,33101.632586,38618.57135,45054.999908,41377.040732,44135.510114,45054.999908,48732.959084,45054.999908,43216.02032,40457.550938
89,2022-03-28 00:00:00,45974.489702,36779.591762,42296.530526,47813.46929,51491.428467,46893.979496,55169.387643,60686.326407,61605.816201,...,34021.12238,34940.612174,37699.081556,31262.652998,29423.673409,22067.755057,20228.775469,14711.836705,15631.326499,12872.857117
90,2022-03-29 00:00:00,15631.326499,11033.877529,8275.408146,6436.428558,7355.918352,7355.918352,7355.918352,7355.918352,4597.44897,...,34940.612174,37699.081556,42296.530526,43216.02032,48732.959084,45054.999908,42296.530526,36779.591762,34021.12238,33101.632586
91,2022-03-30 00:00:00,35860.101968,37699.081556,39538.061144,36779.591762,35860.101968,33101.632586,35860.101968,34940.612174,31262.652998,...,39538.061144,38618.57135,36779.591762,36779.591762,29423.673409,24826.224439,25745.714233,27584.693821,29423.673409,26665.204027
92,2022-03-31 00:00:00,23906.734645,22067.755057,23906.734645,21148.265263,16550.816293,16550.816293,19309.285675,14711.836705,15631.326499,...,115855.71405,114936.224256,110338.775286,104821.836521,90109.999817,80915.101876,82754.081464,85512.550846,89190.510023,80915.101876

In [70]:
str_datetime

'2022/3/31/23/30'

In [56]:
df['0']

3     2022-01-01 00:00:00
4     2022-01-02 00:00:00
5     2022-01-03 00:00:00
6     2022-01-04 00:00:00
7     2022-01-05 00:00:00
             ...
88    2022-03-27 00:00:00
89    2022-03-28 00:00:00
90    2022-03-29 00:00:00
91    2022-03-30 00:00:00
92    2022-03-31 00:00:00
Name: 0, Length: 90, dtype: object

In [73]:
datetime_list

[datetime.datetime(2022, 1, 1, 0, 0),
 datetime.datetime(2022, 1, 1, 0, 30),
 datetime.datetime(2022, 1, 1, 1, 0),
 datetime.datetime(2022, 1, 1, 1, 30),
 datetime.datetime(2022, 1, 1, 2, 0),
 datetime.datetime(2022, 1, 1, 2, 30),
 datetime.datetime(2022, 1, 1, 3, 0),
 datetime.datetime(2022, 1, 1, 3, 30),
 datetime.datetime(2022, 1, 1, 4, 0),
 datetime.datetime(2022, 1, 1, 4, 30),
 datetime.datetime(2022, 1, 1, 5, 0),
 datetime.datetime(2022, 1, 1, 5, 30),
 datetime.datetime(2022, 1, 1, 6, 0),
 datetime.datetime(2022, 1, 1, 6, 30),
 datetime.datetime(2022, 1, 1, 7, 0),
 datetime.datetime(2022, 1, 1, 7, 30),
 datetime.datetime(2022, 1, 1, 8, 0),
 datetime.datetime(2022, 1, 1, 8, 30),
 datetime.datetime(2022, 1, 1, 9, 0),
 datetime.datetime(2022, 1, 1, 9, 30),
 datetime.datetime(2022, 1, 1, 10, 0),
 datetime.datetime(2022, 1, 1, 10, 30),
 datetime.datetime(2022, 1, 1, 11, 0),
 datetime.datetime(2022, 1, 1, 11, 30),
 datetime.datetime(2022, 1, 1, 12, 0),
 datetime.datetime(2022, 1, 1, 12, 30),
 datetime.datetime(2022, 1, 1, 13, 0),
 datetime.datetime(2022, 1, 1, 13, 30),
 datetime.datetime(2022, 1, 1, 14, 0),
 datetime.datetime(2022, 1, 1, 14, 30),
 datetime.datetime(2022, 1, 1, 15, 0),
 datetime.datetime(2022, 1, 1, 15, 30),
 datetime.datetime(2022, 1, 1, 16, 0),
 datetime.datetime(2022, 1, 1, 16, 30),
 datetime.datetime(2022, 1, 1, 17, 0),
 datetime.datetime(2022, 1, 1, 17, 30),
 datetime.datetime(2022, 1, 1, 18, 0),
 datetime.datetime(2022, 1, 1, 18, 30),
 datetime.datetime(2022, 1, 1, 19, 0),
 datetime.datetime(2022, 1, 1, 19, 30),
 datetime.datetime(2022, 1, 1, 20, 0),
 datetime.datetime(2022, 1, 1, 20, 30),
 datetime.datetime(2022, 1, 1, 21, 0),
 datetime.datetime(2022, 1, 1, 21, 30),
 datetime.datetime(2022, 1, 1, 22, 0),
 datetime.datetime(2022, 1, 1, 22, 30),
 datetime.datetime(2022, 1, 1, 23, 0),
 datetime.datetime(2022, 1, 1, 23, 30),
 datetime.datetime(2022, 1, 2, 0, 0),
 datetime.datetime(2022, 1, 2, 0, 30),
 datetime.datetime(2022, 1, 2, 1, 0),
 datetime.datetime(2022, 1, 2, 1, 30),
 datetime.datetime(2022, 1, 2, 2, 0),
 datetime.datetime(2022, 1, 2, 2, 30),
 datetime.datetime(2022, 1, 2, 3, 0),
 datetime.datetime(2022, 1, 2, 3, 30),
 datetime.datetime(2022, 1, 2, 4, 0),
 datetime.datetime(2022, 1, 2, 4, 30),
 datetime.datetime(2022, 1, 2, 5, 0),
 datetime.datetime(2022, 1, 2, 5, 30),
 datetime.datetime(2022, 1, 2, 6, 0),
 datetime.datetime(2022, 1, 2, 6, 30),
 datetime.datetime(2022, 1, 2, 7, 0),
 datetime.datetime(2022, 1, 2, 7, 30),
 datetime.datetime(2022, 1, 2, 8, 0),
 datetime.datetime(2022, 1, 2, 8, 30),
 datetime.datetime(2022, 1, 2, 9, 0),
 datetime.datetime(2022, 1, 2, 9, 30),
 datetime.datetime(2022, 1, 2, 10, 0),
 datetime.datetime(2022, 1, 2, 10, 30),
 datetime.datetime(2022, 1, 2, 11, 0),
 datetime.datetime(2022, 1, 2, 11, 30),
 datetime.datetime(2022, 1, 2, 12, 0),
 datetime.datetime(2022, 1, 2, 12, 30),
 datetime.datetime(2022, 1, 2, 13, 0),
 datetime.datetime(2022, 1, 2, 13, 30),
 datetime.datetime(2022, 1, 2, 14, 0),
 datetime.datetime(2022, 1, 2, 14, 30),
 datetime.datetime(2022, 1, 2, 15, 0),
 datetime.datetime(2022, 1, 2, 15, 30),
 datetime.datetime(2022, 1, 2, 16, 0),
 datetime.datetime(2022, 1, 2, 16, 30),
 datetime.datetime(2022, 1, 2, 17, 0),
 datetime.datetime(2022, 1, 2, 17, 30),
 datetime.datetime(2022, 1, 2, 18, 0),
 datetime.datetime(2022, 1, 2, 18, 30),
 datetime.datetime(2022, 1, 2, 19, 0),
 datetime.datetime(2022, 1, 2, 19, 30),
 datetime.datetime(2022, 1, 2, 20, 0),
 datetime.datetime(2022, 1, 2, 20, 30),
 datetime.datetime(2022, 1, 2, 21, 0),
 datetime.datetime(2022, 1, 2, 21, 30),
 datetime.datetime(2022, 1, 2, 22, 0),
 datetime.datetime(2022, 1, 2, 22, 30),
 datetime.datetime(2022, 1, 2, 23, 0),
 datetime.datetime(2022, 1, 2, 23, 30),
 datetime.datetime(2022, 1, 3, 0, 0),
 datetime.datetime(2022, 1, 3, 0, 30),
 datetime.datetime(2022, 1, 3, 1, 0),
 datetime.datetime(2022, 1, 3, 1, 30),
 datetime.datetime(2022, 1, 3, 2, 0),
 datetime.datetime(2022, 1, 3, 2, 30),
 datetime.datetime(2022, 1, 3, 3, 0),
 datetime.datetime(2022, 1, 3, 3, 30),
 datetime.datetime(2022, 1, 3, 4, 0),
 datetime.datetime(2022, 1, 3, 4, 30),
 datetime.datetime(2022, 1, 3, 5, 0),
 datetime.datetime(2022, 1, 3, 5, 30),
 datetime.datetime(2022, 1, 3, 6, 0),
 datetime.datetime(2022, 1, 3, 6, 30),
 datetime.datetime(2022, 1, 3, 7, 0),
 datetime.datetime(2022, 1, 3, 7, 30),
 datetime.datetime(2022, 1, 3, 8, 0),
 datetime.datetime(2022, 1, 3, 8, 30),
 datetime.datetime(2022, 1, 3, 9, 0),
 datetime.datetime(2022, 1, 3, 9, 30),
 datetime.datetime(2022, 1, 3, 10, 0),
 datetime.datetime(2022, 1, 3, 10, 30),
 datetime.datetime(2022, 1, 3, 11, 0),
 datetime.datetime(2022, 1, 3, 11, 30),
 datetime.datetime(2022, 1, 3, 12, 0),
 datetime.datetime(2022, 1, 3, 12, 30),
 datetime.datetime(2022, 1, 3, 13, 0),
 datetime.datetime(2022, 1, 3, 13, 30),
 datetime.datetime(2022, 1, 3, 14, 0),
 datetime.datetime(2022, 1, 3, 14, 30),
 datetime.datetime(2022, 1, 3, 15, 0),
 datetime.datetime(2022, 1, 3, 15, 30),
 datetime.datetime(2022, 1, 3, 16, 0),
 datetime.datetime(2022, 1, 3, 16, 30),
 datetime.datetime(2022, 1, 3, 17, 0),
 datetime.datetime(2022, 1, 3, 17, 30),
 datetime.datetime(2022, 1, 3, 18, 0),
 datetime.datetime(2022, 1, 3, 18, 30),
 datetime.datetime(2022, 1, 3, 19, 0),
 datetime.datetime(2022, 1, 3, 19, 30),
 datetime.datetime(2022, 1, 3, 20, 0),
 datetime.datetime(2022, 1, 3, 20, 30),
 datetime.datetime(2022, 1, 3, 21, 0),
 datetime.datetime(2022, 1, 3, 21, 30),
 datetime.datetime(2022, 1, 3, 22, 0),
 datetime.datetime(2022, 1, 3, 22, 30),
 datetime.datetime(2022, 1, 3, 23, 0),
 datetime.datetime(2022, 1, 3, 23, 30),
 datetime.datetime(2022, 1, 4, 0, 0),
 datetime.datetime(2022, 1, 4, 0, 30),
 datetime.datetime(2022, 1, 4, 1, 0),
 datetime.datetime(2022, 1, 4, 1, 30),
 datetime.datetime(2022, 1, 4, 2, 0),
 datetime.datetime(2022, 1, 4, 2, 30),
 datetime.datetime(2022, 1, 4, 3, 0),
 datetime.datetime(2022, 1, 4, 3, 30),
 datetime.datetime(2022, 1, 4, 4, 0),
 datetime.datetime(2022, 1, 4, 4, 30),
 datetime.datetime(2022, 1, 4, 5, 0),
 datetime.datetime(2022, 1, 4, 5, 30),
 datetime.datetime(2022, 1, 4, 6, 0),
 datetime.datetime(2022, 1, 4, 6, 30),
 datetime.datetime(2022, 1, 4, 7, 0),
 datetime.datetime(2022, 1, 4, 7, 30),
 datetime.datetime(2022, 1, 4, 8, 0),
 datetime.datetime(2022, 1, 4, 8, 30),
 datetime.datetime(2022, 1, 4, 9, 0),
 datetime.datetime(2022, 1, 4, 9, 30),
 datetime.datetime(2022, 1, 4, 10, 0),
 datetime.datetime(2022, 1, 4, 10, 30),
 datetime.datetime(2022, 1, 4, 11, 0),
 datetime.datetime(2022, 1, 4, 11, 30),
 datetime.datetime(2022, 1, 4, 12, 0),
 datetime.datetime(2022, 1, 4, 12, 30),
 datetime.datetime(2022, 1, 4, 13, 0),
 datetime.datetime(2022, 1, 4, 13, 30),
 datetime.datetime(2022, 1, 4, 14, 0),
 datetime.datetime(2022, 1, 4, 14, 30),
 datetime.datetime(2022, 1, 4, 15, 0),
 datetime.datetime(2022, 1, 4, 15, 30),
 datetime.datetime(2022, 1, 4, 16, 0),
 datetime.datetime(2022, 1, 4, 16, 30),
 datetime.datetime(2022, 1, 4, 17, 0),
 datetime.datetime(2022, 1, 4, 17, 30),
 datetime.datetime(2022, 1, 4, 18, 0),
 datetime.datetime(2022, 1, 4, 18, 30),
 datetime.datetime(2022, 1, 4, 19, 0),
 datetime.datetime(2022, 1, 4, 19, 30),
 datetime.datetime(2022, 1, 4, 20, 0),
 datetime.datetime(2022, 1, 4, 20, 30),
 datetime.datetime(2022, 1, 4, 21, 0),
 datetime.datetime(2022, 1, 4, 21, 30),
 datetime.datetime(2022, 1, 4, 22, 0),
 datetime.datetime(2022, 1, 4, 22, 30),
 datetime.datetime(2022, 1, 4, 23, 0),
 datetime.datetime(2022, 1, 4, 23, 30),
 datetime.datetime(2022, 1, 5, 0, 0),
 datetime.datetime(2022, 1, 5, 0, 30),
 datetime.datetime(2022, 1, 5, 1, 0),
 datetime.datetime(2022, 1, 5, 1, 30),
 datetime.datetime(2022, 1, 5, 2, 0),
 datetime.datetime(2022, 1, 5, 2, 30),
 datetime.datetime(2022, 1, 5, 3, 0),
 datetime.datetime(2022, 1, 5, 3, 30),
 datetime.datetime(2022, 1, 5, 4, 0),
 datetime.datetime(2022, 1, 5, 4, 30),
 datetime.datetime(2022, 1, 5, 5, 0),
 datetime.datetime(2022, 1, 5, 5, 30),
 datetime.datetime(2022, 1, 5, 6, 0),
 datetime.datetime(2022, 1, 5, 6, 30),
 datetime.datetime(2022, 1, 5, 7, 0),
 datetime.datetime(2022, 1, 5, 7, 30),
 datetime.datetime(2022, 1, 5, 8, 0),
 datetime.datetime(2022, 1, 5, 8, 30),
 datetime.datetime(2022, 1, 5, 9, 0),
 datetime.datetime(2022, 1, 5, 9, 30),
 datetime.datetime(2022, 1, 5, 10, 0),
 datetime.datetime(2022, 1, 5, 10, 30),
 datetime.datetime(2022, 1, 5, 11, 0),
 datetime.datetime(2022, 1, 5, 11, 30),
 datetime.datetime(2022, 1, 5, 12, 0),
 datetime.datetime(2022, 1, 5, 12, 30),
 datetime.datetime(2022, 1, 5, 13, 0),
 datetime.datetime(2022, 1, 5, 13, 30),
 datetime.datetime(2022, 1, 5, 14, 0),
 datetime.datetime(2022, 1, 5, 14, 30),
 datetime.datetime(2022, 1, 5, 15, 0),
 datetime.datetime(2022, 1, 5, 15, 30),
 datetime.datetime(2022, 1, 5, 16, 0),
 datetime.datetime(2022, 1, 5, 16, 30),
 datetime.datetime(2022, 1, 5, 17, 0),
 datetime.datetime(2022, 1, 5, 17, 30),
 datetime.datetime(2022, 1, 5, 18, 0),
 datetime.datetime(2022, 1, 5, 18, 30),
 datetime.datetime(2022, 1, 5, 19, 0),
 datetime.datetime(2022, 1, 5, 19, 30),
 datetime.datetime(2022, 1, 5, 20, 0),
 datetime.datetime(2022, 1, 5, 20, 30),
 datetime.datetime(2022, 1, 5, 21, 0),
 datetime.datetime(2022, 1, 5, 21, 30),
 datetime.datetime(2022, 1, 5, 22, 0),
 datetime.datetime(2022, 1, 5, 22, 30),
 datetime.datetime(2022, 1, 5, 23, 0),
 datetime.datetime(2022, 1, 5, 23, 30),
 datetime.datetime(2022, 1, 6, 0, 0),
 datetime.datetime(2022, 1, 6, 0, 30),
 datetime.datetime(2022, 1, 6, 1, 0),
 datetime.datetime(2022, 1, 6, 1, 30),
 datetime.datetime(2022, 1, 6, 2, 0),
 datetime.datetime(2022, 1, 6, 2, 30),
 datetime.datetime(2022, 1, 6, 3, 0),
 datetime.datetime(2022, 1, 6, 3, 30),
 datetime.datetime(2022, 1, 6, 4, 0),
 datetime.datetime(2022, 1, 6, 4, 30),
 datetime.datetime(2022, 1, 6, 5, 0),
 datetime.datetime(2022, 1, 6, 5, 30),
 datetime.datetime(2022, 1, 6, 6, 0),
 datetime.datetime(2022, 1, 6, 6, 30),
 datetime.datetime(2022, 1, 6, 7, 0),
 datetime.datetime(2022, 1, 6, 7, 30),
 datetime.datetime(2022, 1, 6, 8, 0),
 datetime.datetime(2022, 1, 6, 8, 30),
 datetime.datetime(2022, 1, 6, 9, 0),
 datetime.datetime(2022, 1, 6, 9, 30),
 datetime.datetime(2022, 1, 6, 10, 0),
 datetime.datetime(2022, 1, 6, 10, 30),
 datetime.datetime(2022, 1, 6, 11, 0),
 datetime.datetime(2022, 1, 6, 11, 30),
 datetime.datetime(2022, 1, 6, 12, 0),
 datetime.datetime(2022, 1, 6, 12, 30),
 datetime.datetime(2022, 1, 6, 13, 0),
 datetime.datetime(2022, 1, 6, 13, 30),
 datetime.datetime(2022, 1, 6, 14, 0),
 datetime.datetime(2022, 1, 6, 14, 30),
 datetime.datetime(2022, 1, 6, 15, 0),
 datetime.datetime(2022, 1, 6, 15, 30),
 datetime.datetime(2022, 1, 6, 16, 0),
 datetime.datetime(2022, 1, 6, 16, 30),
 datetime.datetime(2022, 1, 6, 17, 0),
 datetime.datetime(2022, 1, 6, 17, 30),
 datetime.datetime(2022, 1, 6, 18, 0),
 datetime.datetime(2022, 1, 6, 18, 30),
 datetime.datetime(2022, 1, 6, 19, 0),
 datetime.datetime(2022, 1, 6, 19, 30),
 datetime.datetime(2022, 1, 6, 20, 0),
 datetime.datetime(2022, 1, 6, 20, 30),
 datetime.datetime(2022, 1, 6, 21, 0),
 datetime.datetime(2022, 1, 6, 21, 30),
 datetime.datetime(2022, 1, 6, 22, 0),
 datetime.datetime(2022, 1, 6, 22, 30),
 datetime.datetime(2022, 1, 6, 23, 0),
 datetime.datetime(2022, 1, 6, 23, 30),
 datetime.datetime(2022, 1, 7, 0, 0),
 datetime.datetime(2022, 1, 7, 0, 30),
 datetime.datetime(2022, 1, 7, 1, 0),
 datetime.datetime(2022, 1, 7, 1, 30),
 datetime.datetime(2022, 1, 7, 2, 0),
 datetime.datetime(2022, 1, 7, 2, 30),
 datetime.datetime(2022, 1, 7, 3, 0),
 datetime.datetime(2022, 1, 7, 3, 30),
 datetime.datetime(2022, 1, 7, 4, 0),
 datetime.datetime(2022, 1, 7, 4, 30),
 datetime.datetime(2022, 1, 7, 5, 0),
 datetime.datetime(2022, 1, 7, 5, 30),
 datetime.datetime(2022, 1, 7, 6, 0),
 datetime.datetime(2022, 1, 7, 6, 30),
 datetime.datetime(2022, 1, 7, 7, 0),
 datetime.datetime(2022, 1, 7, 7, 30),
 datetime.datetime(2022, 1, 7, 8, 0),
 datetime.datetime(2022, 1, 7, 8, 30),
 datetime.datetime(2022, 1, 7, 9, 0),
 datetime.datetime(2022, 1, 7, 9, 30),
 datetime.datetime(2022, 1, 7, 10, 0),
 datetime.datetime(2022, 1, 7, 10, 30),
 datetime.datetime(2022, 1, 7, 11, 0),
 datetime.datetime(2022, 1, 7, 11, 30),
 datetime.datetime(2022, 1, 7, 12, 0),
 datetime.datetime(2022, 1, 7, 12, 30),
 datetime.datetime(2022, 1, 7, 13, 0),
 datetime.datetime(2022, 1, 7, 13, 30),
 datetime.datetime(2022, 1, 7, 14, 0),
 datetime.datetime(2022, 1, 7, 14, 30),
 datetime.datetime(2022, 1, 7, 15, 0),
 datetime.datetime(2022, 1, 7, 15, 30),
 datetime.datetime(2022, 1, 7, 16, 0),
 datetime.datetime(2022, 1, 7, 16, 30),
 datetime.datetime(2022, 1, 7, 17, 0),
 datetime.datetime(2022, 1, 7, 17, 30),
 datetime.datetime(2022, 1, 7, 18, 0),
 datetime.datetime(2022, 1, 7, 18, 30),
 datetime.datetime(2022, 1, 7, 19, 0),
 datetime.datetime(2022, 1, 7, 19, 30),
 datetime.datetime(2022, 1, 7, 20, 0),
 datetime.datetime(2022, 1, 7, 20, 30),
 datetime.datetime(2022, 1, 7, 21, 0),
 datetime.datetime(2022, 1, 7, 21, 30),
 datetime.datetime(2022, 1, 7, 22, 0),
 datetime.datetime(2022, 1, 7, 22, 30),
 datetime.datetime(2022, 1, 7, 23, 0),
 datetime.datetime(2022, 1, 7, 23, 30),
 datetime.datetime(2022, 1, 8, 0, 0),
 datetime.datetime(2022, 1, 8, 0, 30),
 datetime.datetime(2022, 1, 8, 1, 0),
 datetime.datetime(2022, 1, 8, 1, 30),
 datetime.datetime(2022, 1, 8, 2, 0),
 datetime.datetime(2022, 1, 8, 2, 30),
 datetime.datetime(2022, 1, 8, 3, 0),
 datetime.datetime(2022, 1, 8, 3, 30),
 datetime.datetime(2022, 1, 8, 4, 0),
 datetime.datetime(2022, 1, 8, 4, 30),
 datetime.datetime(2022, 1, 8, 5, 0),
 datetime.datetime(2022, 1, 8, 5, 30),
 datetime.datetime(2022, 1, 8, 6, 0),
 datetime.datetime(2022, 1, 8, 6, 30),
 datetime.datetime(2022, 1, 8, 7, 0),
 datetime.datetime(2022, 1, 8, 7, 30),
 datetime.datetime(2022, 1, 8, 8, 0),
 datetime.datetime(2022, 1, 8, 8, 30),
 datetime.datetime(2022, 1, 8, 9, 0),
 datetime.datetime(2022, 1, 8, 9, 30),
 datetime.datetime(2022, 1, 8, 10, 0),
 datetime.datetime(2022, 1, 8, 10, 30),
 datetime.datetime(2022, 1, 8, 11, 0),
 datetime.datetime(2022, 1, 8, 11, 30),
 datetime.datetime(2022, 1, 8, 12, 0),
 datetime.datetime(2022, 1, 8, 12, 30),
 datetime.datetime(2022, 1, 8, 13, 0),
 datetime.datetime(2022, 1, 8, 13, 30),
 datetime.datetime(2022, 1, 8, 14, 0),
 datetime.datetime(2022, 1, 8, 14, 30),
 datetime.datetime(2022, 1, 8, 15, 0),
 datetime.datetime(2022, 1, 8, 15, 30),
 datetime.datetime(2022, 1, 8, 16, 0),
 datetime.datetime(2022, 1, 8, 16, 30),
 datetime.datetime(2022, 1, 8, 17, 0),
 datetime.datetime(2022, 1, 8, 17, 30),
 datetime.datetime(2022, 1, 8, 18, 0),
 datetime.datetime(2022, 1, 8, 18, 30),
 datetime.datetime(2022, 1, 8, 19, 0),
 datetime.datetime(2022, 1, 8, 19, 30),
 datetime.datetime(2022, 1, 8, 20, 0),
 datetime.datetime(2022, 1, 8, 20, 30),
 datetime.datetime(2022, 1, 8, 21, 0),
 datetime.datetime(2022, 1, 8, 21, 30),
 datetime.datetime(2022, 1, 8, 22, 0),
 datetime.datetime(2022, 1, 8, 22, 30),
 datetime.datetime(2022, 1, 8, 23, 0),
 datetime.datetime(2022, 1, 8, 23, 30),
 datetime.datetime(2022, 1, 9, 0, 0),
 datetime.datetime(2022, 1, 9, 0, 30),
 datetime.datetime(2022, 1, 9, 1, 0),
 datetime.datetime(2022, 1, 9, 1, 30),
 datetime.datetime(2022, 1, 9, 2, 0),
 datetime.datetime(2022, 1, 9, 2, 30),
 datetime.datetime(2022, 1, 9, 3, 0),
 datetime.datetime(2022, 1, 9, 3, 30),
 datetime.datetime(2022, 1, 9, 4, 0),
 datetime.datetime(2022, 1, 9, 4, 30),
 datetime.datetime(2022, 1, 9, 5, 0),
 datetime.datetime(2022, 1, 9, 5, 30),
 datetime.datetime(2022, 1, 9, 6, 0),
 datetime.datetime(2022, 1, 9, 6, 30),
 datetime.datetime(2022, 1, 9, 7, 0),
 datetime.datetime(2022, 1, 9, 7, 30),
 datetime.datetime(2022, 1, 9, 8, 0),
 datetime.datetime(2022, 1, 9, 8, 30),
 datetime.datetime(2022, 1, 9, 9, 0),
 datetime.datetime(2022, 1, 9, 9, 30),
 datetime.datetime(2022, 1, 9, 10, 0),
 datetime.datetime(2022, 1, 9, 10, 30),
 datetime.datetime(2022, 1, 9, 11, 0),
 datetime.datetime(2022, 1, 9, 11, 30),
 datetime.datetime(2022, 1, 9, 12, 0),
 datetime.datetime(2022, 1, 9, 12, 30),
 datetime.datetime(2022, 1, 9, 13, 0),
 datetime.datetime(2022, 1, 9, 13, 30),
 datetime.datetime(2022, 1, 9, 14, 0),
 datetime.datetime(2022, 1, 9, 14, 30),
 datetime.datetime(2022, 1, 9, 15, 0),
 datetime.datetime(2022, 1, 9, 15, 30),
 datetime.datetime(2022, 1, 9, 16, 0),
 datetime.datetime(2022, 1, 9, 16, 30),
 datetime.datetime(2022, 1, 9, 17, 0),
 datetime.datetime(2022, 1, 9, 17, 30),
 datetime.datetime(2022, 1, 9, 18, 0),
 datetime.datetime(2022, 1, 9, 18, 30),
 datetime.datetime(2022, 1, 9, 19, 0),
 datetime.datetime(2022, 1, 9, 19, 30),
 datetime.datetime(2022, 1, 9, 20, 0),
 datetime.datetime(2022, 1, 9, 20, 30),
 datetime.datetime(2022, 1, 9, 21, 0),
 datetime.datetime(2022, 1, 9, 21, 30),
 datetime.datetime(2022, 1, 9, 22, 0),
 datetime.datetime(2022, 1, 9, 22, 30),
 datetime.datetime(2022, 1, 9, 23, 0),
 datetime.datetime(2022, 1, 9, 23, 30),
 datetime.datetime(2022, 1, 10, 0, 0),
 datetime.datetime(2022, 1, 10, 0, 30),
 datetime.datetime(2022, 1, 10, 1, 0),
 datetime.datetime(2022, 1, 10, 1, 30),
 datetime.datetime(2022, 1, 10, 2, 0),
 datetime.datetime(2022, 1, 10, 2, 30),
 datetime.datetime(2022, 1, 10, 3, 0),
 datetime.datetime(2022, 1, 10, 3, 30),
 datetime.datetime(2022, 1, 10, 4, 0),
 datetime.datetime(2022, 1, 10, 4, 30),
 datetime.datetime(2022, 1, 10, 5, 0),
 datetime.datetime(2022, 1, 10, 5, 30),
 datetime.datetime(2022, 1, 10, 6, 0),
 datetime.datetime(2022, 1, 10, 6, 30),
 datetime.datetime(2022, 1, 10, 7, 0),
 datetime.datetime(2022, 1, 10, 7, 30),
 datetime.datetime(2022, 1, 10, 8, 0),
 datetime.datetime(2022, 1, 10, 8, 30),
 datetime.datetime(2022, 1, 10, 9, 0),
 datetime.datetime(2022, 1, 10, 9, 30),
 datetime.datetime(2022, 1, 10, 10, 0),
 datetime.datetime(2022, 1, 10, 10, 30),
 datetime.datetime(2022, 1, 10, 11, 0),
 datetime.datetime(2022, 1, 10, 11, 30),
 datetime.datetime(2022, 1, 10, 12, 0),
 datetime.datetime(2022, 1, 10, 12, 30),
 datetime.datetime(2022, 1, 10, 13, 0),
 datetime.datetime(2022, 1, 10, 13, 30),
 datetime.datetime(2022, 1, 10, 14, 0),
 datetime.datetime(2022, 1, 10, 14, 30),
 datetime.datetime(2022, 1, 10, 15, 0),
 datetime.datetime(2022, 1, 10, 15, 30),
 datetime.datetime(2022, 1, 10, 16, 0),
 datetime.datetime(2022, 1, 10, 16, 30),
 datetime.datetime(2022, 1, 10, 17, 0),
 datetime.datetime(2022, 1, 10, 17, 30),
 datetime.datetime(2022, 1, 10, 18, 0),
 datetime.datetime(2022, 1, 10, 18, 30),
 datetime.datetime(2022, 1, 10, 19, 0),
 datetime.datetime(2022, 1, 10, 19, 30),
 datetime.datetime(2022, 1, 10, 20, 0),
 datetime.datetime(2022, 1, 10, 20, 30),
 datetime.datetime(2022, 1, 10, 21, 0),
 datetime.datetime(2022, 1, 10, 21, 30),
 datetime.datetime(2022, 1, 10, 22, 0),
 datetime.datetime(2022, 1, 10, 22, 30),
 datetime.datetime(2022, 1, 10, 23, 0),
 datetime.datetime(2022, 1, 10, 23, 30),
 datetime.datetime(2022, 1, 11, 0, 0),
 datetime.datetime(2022, 1, 11, 0, 30),
 datetime.datetime(2022, 1, 11, 1, 0),
 datetime.datetime(2022, 1, 11, 1, 30),
 datetime.datetime(2022, 1, 11, 2, 0),
 datetime.datetime(2022, 1, 11, 2, 30),
 datetime.datetime(2022, 1, 11, 3, 0),
 datetime.datetime(2022, 1, 11, 3, 30),
 datetime.datetime(2022, 1, 11, 4, 0),
 datetime.datetime(2022, 1, 11, 4, 30),
 datetime.datetime(2022, 1, 11, 5, 0),
 datetime.datetime(2022, 1, 11, 5, 30),
 datetime.datetime(2022, 1, 11, 6, 0),
 datetime.datetime(2022, 1, 11, 6, 30),
 datetime.datetime(2022, 1, 11, 7, 0),
 datetime.datetime(2022, 1, 11, 7, 30),
 datetime.datetime(2022, 1, 11, 8, 0),
 datetime.datetime(2022, 1, 11, 8, 30),
 datetime.datetime(2022, 1, 11, 9, 0),
 datetime.datetime(2022, 1, 11, 9, 30),
 datetime.datetime(2022, 1, 11, 10, 0),
 datetime.datetime(2022, 1, 11, 10, 30),
 datetime.datetime(2022, 1, 11, 11, 0),
 datetime.datetime(2022, 1, 11, 11, 30),
 datetime.datetime(2022, 1, 11, 12, 0),
 datetime.datetime(2022, 1, 11, 12, 30),
 datetime.datetime(2022, 1, 11, 13, 0),
 datetime.datetime(2022, 1, 11, 13, 30),
 datetime.datetime(2022, 1, 11, 14, 0),

In [39]:
df[3:]['九州エリアにおけるＦＩＴ特例①電源　風力発電実績値（離島除き）'].values

array([datetime.datetime(2022, 1, 3, 0, 0),
       datetime.datetime(2022, 1, 4, 0, 0),
       datetime.datetime(2022, 1, 5, 0, 0),
       datetime.datetime(2022, 1, 6, 0, 0),
       datetime.datetime(2022, 1, 7, 0, 0),
       datetime.datetime(2022, 1, 8, 0, 0),
       datetime.datetime(2022, 1, 9, 0, 0),
       datetime.datetime(2022, 1, 10, 0, 0),
       datetime.datetime(2022, 1, 11, 0, 0),
       datetime.datetime(2022, 1, 12, 0, 0),
       datetime.datetime(2022, 1, 13, 0, 0),
       datetime.datetime(2022, 1, 14, 0, 0),
       datetime.datetime(2022, 1, 15, 0, 0),
       datetime.datetime(2022, 1, 16, 0, 0),
       datetime.datetime(2022, 1, 17, 0, 0),
       datetime.datetime(2022, 1, 18, 0, 0),
       datetime.datetime(2022, 1, 19, 0, 0),
       datetime.datetime(2022, 1, 20, 0, 0),
       datetime.datetime(2022, 1, 21, 0, 0),
       datetime.datetime(2022, 1, 22, 0, 0),
       datetime.datetime(2022, 1, 23, 0, 0),
       datetime.datetime(2022, 1, 24, 0, 0),
       datetime.datetime(2022, 1, 25, 0, 0),
       datetime.datetime(2022, 1, 26, 0, 0),
       datetime.datetime(2022, 1, 27, 0, 0),
       datetime.datetime(2022, 1, 28, 0, 0),
       datetime.datetime(2022, 1, 29, 0, 0),
       datetime.datetime(2022, 1, 30, 0, 0),
       datetime.datetime(2022, 1, 31, 0, 0),
       datetime.datetime(2022, 2, 1, 0, 0),
       datetime.datetime(2022, 2, 2, 0, 0),
       datetime.datetime(2022, 2, 3, 0, 0),
       datetime.datetime(2022, 2, 4, 0, 0),
       datetime.datetime(2022, 2, 5, 0, 0),
       datetime.datetime(2022, 2, 6, 0, 0),
       datetime.datetime(2022, 2, 7, 0, 0),
       datetime.datetime(2022, 2, 8, 0, 0),
       datetime.datetime(2022, 2, 9, 0, 0),
       datetime.datetime(2022, 2, 10, 0, 0),
       datetime.datetime(2022, 2, 11, 0, 0),
       datetime.datetime(2022, 2, 12, 0, 0),
       datetime.datetime(2022, 2, 13, 0, 0),
       datetime.datetime(2022, 2, 14, 0, 0),
       datetime.datetime(2022, 2, 15, 0, 0),
       datetime.datetime(2022, 2, 16, 0, 0),
       datetime.datetime(2022, 2, 17, 0, 0),
       datetime.datetime(2022, 2, 18, 0, 0),
       datetime.datetime(2022, 2, 19, 0, 0),
       datetime.datetime(2022, 2, 20, 0, 0),
       datetime.datetime(2022, 2, 21, 0, 0),
       datetime.datetime(2022, 2, 22, 0, 0),
       datetime.datetime(2022, 2, 23, 0, 0),
       datetime.datetime(2022, 2, 24, 0, 0),
       datetime.datetime(2022, 2, 25, 0, 0),
       datetime.datetime(2022, 2, 26, 0, 0),
       datetime.datetime(2022, 2, 27, 0, 0),
       datetime.datetime(2022, 2, 28, 0, 0),
       datetime.datetime(2022, 3, 1, 0, 0),
       datetime.datetime(2022, 3, 2, 0, 0),
       datetime.datetime(2022, 3, 3, 0, 0),
       datetime.datetime(2022, 3, 4, 0, 0),
       datetime.datetime(2022, 3, 5, 0, 0),
       datetime.datetime(2022, 3, 6, 0, 0),
       datetime.datetime(2022, 3, 7, 0, 0),
       datetime.datetime(2022, 3, 8, 0, 0),
       datetime.datetime(2022, 3, 9, 0, 0),
       datetime.datetime(2022, 3, 10, 0, 0),
       datetime.datetime(2022, 3, 11, 0, 0),
       datetime.datetime(2022, 3, 12, 0, 0),
       datetime.datetime(2022, 3, 13, 0, 0),
       datetime.datetime(2022, 3, 14, 0, 0),
       datetime.datetime(2022, 3, 15, 0, 0),
       datetime.datetime(2022, 3, 16, 0, 0),
       datetime.datetime(2022, 3, 17, 0, 0),
       datetime.datetime(2022, 3, 18, 0, 0),
       datetime.datetime(2022, 3, 19, 0, 0),
       datetime.datetime(2022, 3, 20, 0, 0),
       datetime.datetime(2022, 3, 21, 0, 0),
       datetime.datetime(2022, 3, 22, 0, 0),
       datetime.datetime(2022, 3, 23, 0, 0),
       datetime.datetime(2022, 3, 24, 0, 0),
       datetime.datetime(2022, 3, 25, 0, 0),
       datetime.datetime(2022, 3, 26, 0, 0),
       datetime.datetime(2022, 3, 27, 0, 0),
       datetime.datetime(2022, 3, 28, 0, 0),
       datetime.datetime(2022, 3, 29, 0, 0),
       datetime.datetime(2022, 3, 30, 0, 0),
       datetime.datetime(2022, 3, 31, 0, 0)], dtype=object)

In [47]:
df

,九州エリアにおけるＦＩＴ特例①電源 風力発電実績値（離島除き）,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48
2,NaN,00:00:00,00:30:00,01:00:00,01:30:00,02:00:00,02:30:00,03:00:00,03:30:00,04:00:00,...,19:00:00,19:30:00,20:00:00,20:30:00,21:00:00,21:30:00,22:00:00,22:30:00,23:00:00,23:30:00
3,2022-01-01 00:00:00,57782.589713,55195.309577,52608.02944,49158.322592,49158.322592,50883.176016,50883.176016,47433.469167,48295.895879,...,2587.280136,1724.853424,2587.280136,2587.280136,3449.706849,2587.280136,2587.280136,1724.853424,2587.280136,0
4,2022-01-02 00:00:00,1724.853424,862.426712,1724.853424,2587.280136,1724.853424,862.426712,1724.853424,862.426712,3449.706849,...,37084.348622,31909.788349,36221.92191,38809.202046,38809.202046,41396.482182,40534.05547,37946.775334,39671.628758,35359.495197
5,2022-01-03 00:00:00,34497.068485,30184.934925,27597.654788,25872.801364,25872.801364,23285.521228,25010.374652,22423.094515,26735.228076,...,41396.482182,36221.92191,43121.335607,50883.176016,58645.016425,56920.163001,61232.296561,58645.016425,64682.00341,63819.576698
6,2022-01-04 00:00:00,64682.00341,62094.723274,62957.149986,60369.869849,58645.016425,58645.016425,59507.443137,58645.016425,61232.296561,...,43121.335607,37084.348622,31909.788349,25872.801364,22423.094515,14661.254106,12936.400682,15523.680818,16386.107531,14661.254106
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,2022-03-27 00:00:00,76317.652906,78156.632494,72639.69373,74478.673318,68961.734553,71720.203936,79995.612082,75398.163112,63444.795789,...,33101.632586,38618.57135,45054.999908,41377.040732,44135.510114,45054.999908,48732.959084,45054.999908,43216.02032,40457.550938
89,2022-03-28 00:00:00,45974.489702,36779.591762,42296.530526,47813.46929,51491.428467,46893.979496,55169.387643,60686.326407,61605.816201,...,34021.12238,34940.612174,37699.081556,31262.652998,29423.673409,22067.755057,20228.775469,14711.836705,15631.326499,12872.857117
90,2022-03-29 00:00:00,15631.326499,11033.877529,8275.408146,6436.428558,7355.918352,7355.918352,7355.918352,7355.918352,4597.44897,...,34940.612174,37699.081556,42296.530526,43216.02032,48732.959084,45054.999908,42296.530526,36779.591762,34021.12238,33101.632586
91,2022-03-30 00:00:00,35860.101968,37699.081556,39538.061144,36779.591762,35860.101968,33101.632586,35860.101968,34940.612174,31262.652998,...,39538.061144,38618.57135,36779.591762,36779.591762,29423.673409,24826.224439,25745.714233,27584.693821,29423.673409,26665.204027
92,2022-03-31 00:00:00,23906.734645,22067.755057,23906.734645,21148.265263,16550.816293,16550.816293,19309.285675,14711.836705,15631.326499,...,115855.71405,114936.224256,110338.775286,104821.836521,90109.999817,80915.101876,82754.081464,85512.550846,89190.510023,80915.101876

In [44]:
Times = df[0:1].values[0][1:]
Dates=df[3:]['九州エリアにおけるＦＩＴ特例①電源　風力発電実績値（離島除き）'].values

In [46]:
Dates[0].year

2022

In [ ]:
九州エリアにおけるＦＩＴ特例①電源　太陽光発電想定値（離島除き）

In [34]:
df[0:1].values[0][2]

datetime.time(0, 30)

In [ ]:
# https://www.kyuden.co.jp/var/rev0/0364/0254/h30_4-6.xls
# https://www.kyuden.co.jp/var/rev0/0364/0250/2019_4-6.xls
# https://www.kyuden.co.jp/var/rev0/0364/0246/td_2020_4-6.xls
# https://www.kyuden.co.jp/var/rev0/0364/0242/td_2021_4-6.xls

In [8]:
df = pd.read_excel(url,sheet_name='太陽光想定')[3:]

In [12]:
df['九州エリアにおけるＦＩＴ特例①電源　太陽光発電想定値（離島除き）'].values[0]

numpy.datetime64('2022-01-01T00:00:00.000000000')

In [ ]:
# https://www.kyuden.co.jp/var/rev0/0364/0242/td_2021_4-6.xls