In [1]:
import pandas as pd
import numpy as np
import os
import datetime as dt
import calendar
from matplotlib import pyplot as plt
import scipy.stats as stats
import glob


from mpl_toolkits.mplot3d import Axes3D  #3Dplot
import seaborn as sns
import japanize_matplotlib

In [4]:

files = glob.glob('../../../卒論関連書類/データ/king_history/king_history1/*')
version = len(files)-1
df_king =pd.read_csv(f'../../../卒論関連書類/データ/king_history/king_history1/king{version}.csv',converters={'DateTime':pd.to_datetime})

In [8]:
df_king.columns

Index(['DateTime', 'intra_price(円/kWh)', 'spot_price(円/kWh)',
       'gap_price[intra-spot](円/kWh)', 'intra_volume（MWh/h）',
       'spot_volume(kWh)', '北電太陽光想定(MW)', '北電風力想定(MW)', '北電太陽光実績(MW)',
       '北電風力実績(MW)', '九電太陽光想定(kWh)', '九電太陽光実績(kWh)', '九電風力想定(kWh)',
       '九電風力実績(kWh)', '東電太陽光想定(kWh)', '東電太陽光実績(kWh)', '東電風力想定(kWh)',
       '東電風力実績(kWh)', '関電太陽光想定(kWh)', '関電太陽光実績(kWh)', '関電風力想定(kWh)',
       '関電風力実績(kWh)', '中国太陽光想定(kWh)', '中国風力想定(kWh)', '中国太陽光実績(kWh)',
       '中国風力実績(kWh)', '北海道予備率(%)', '東北予備率(%)', '東京予備率(%)', '中部予備率(%)',
       '北陸予備率(%)', '関西予備率(%)', '中国予備率(%)', '四国予備率(%)', '九州予備率(%)'],
      dtype='object')

In [7]:
df_saiene_error = pd.DataFrame()

In [9]:
col_names = ['DateTime','九電太陽光想定(kWh)', '九電太陽光実績(kWh)', '九電風力想定(kWh)',
       '九電風力実績(kWh)', '東電太陽光想定(kWh)', '東電太陽光実績(kWh)', '東電風力想定(kWh)',
       '東電風力実績(kWh)', '関電太陽光想定(kWh)', '関電太陽光実績(kWh)', '関電風力想定(kWh)',
       '関電風力実績(kWh)', '中国太陽光想定(kWh)', '中国風力想定(kWh)', '中国太陽光実績(kWh)',
       '中国風力実績(kWh)']
for name in col_names:
    df_saiene_error[f'{name}']=df_king[f'{name}']

In [11]:
df_saiene_error.dropna()

,DateTime,九電太陽光想定(kWh),九電太陽光実績(kWh),九電風力想定(kWh),九電風力実績(kWh),東電太陽光想定(kWh),東電太陽光実績(kWh),東電風力想定(kWh),東電風力実績(kWh),関電太陽光想定(kWh),関電太陽光実績(kWh),関電風力想定(kWh),関電風力実績(kWh),中国太陽光想定(kWh),中国風力想定(kWh),中国太陽光実績(kWh),中国風力実績(kWh)
0,2018-04-01 00:00:00,0.0,0.0,5889.905000,8909.100000,0.0,0.0,41386.0,50919.0,0.0,0.0,18118.0,21411.0,0.0,39041.0,0.0,38993.0
1,2018-04-01 00:30:00,0.0,0.0,5642.430000,8909.100000,0.0,0.0,41615.0,50733.0,0.0,0.0,18118.0,22064.0,0.0,41624.0,0.0,40253.0
2,2018-04-01 01:00:00,0.0,0.0,5642.430000,6929.300000,0.0,0.0,41793.0,51667.0,0.0,0.0,18118.0,21297.0,0.0,43205.0,0.0,37977.0
3,2018-04-01 01:30:00,0.0,0.0,5444.450000,5939.400000,0.0,0.0,42116.0,57049.0,0.0,0.0,18118.0,19419.0,0.0,43721.0,0.0,39237.0
4,2018-04-01 02:00:00,0.0,0.0,5295.965000,5939.400000,0.0,0.0,42244.0,55349.0,0.0,0.0,18118.0,14621.0,0.0,43721.0,0.0,37666.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79016,2022-09-30 21:30:00,0.0,0.0,1476.377293,900.230057,0.0,0.0,11898.0,44990.0,0.0,0.0,0.0,0.0,0.0,11577.0,0.0,2465.0
79017,2022-09-30 22:00:00,0.0,0.0,672.021737,900.230057,0.0,0.0,11284.0,41454.0,0.0,0.0,0.0,14.0,0.0,10829.0,0.0,4302.0
79018,2022-09-30 22:30:00,0.0,0.0,541.038264,900.230057,0.0,0.0,11000.0,41703.0,0.0,0.0,0.0,99.0,0.0,13621.0,0.0,2447.0
79019,2022-09-30 23:00:00,0.0,0.0,83.271280,900.230057,0.0,0.0,10768.0,35351.0,0.0,0.0,0.0,182.0,0.0,14413.0,0.0,1386.0
79020,2022-09-30 23:30:00,0.0,0.0,694.977604,900.230057,0.0,0.0,10747.0,38281.0,0.0,0.0,0.0,172.0,0.0,14627.0,0.0,2533.0